Fix compilation errors
```
/tmp/miniBUDE/src/main.cpp: In instantiation of 'bool run(const Params&, const std::vector<long unsigned int>&, const std::vector<long unsigned int>&) [with long unsigned int ...Ns = {1, 2, 4, 8, 16, 32, 64, 128}]':
/tmp/miniBUDE/src/main.cpp:654:81:   required from here
/tmp/miniBUDE/src/main.cpp:482:83: error: could not convert '{{1, 2, 4, 8, 16, 32, 64, 128, <lambda closure object>run(const Params&, const std::vector<long unsigned int>&, const std::vector<long unsigned int>&) [with long unsigned int ...Ns = {1, 2, 4, 8, 16, 32, 64, 128}]::<lambda()>{}}, {1, 2, 4, 8, 16, 32, 64, 128, <lambda closure object>run(const Params&, const std::vector<long unsigned int>&, const std::vector<long unsigned int>&) [with long unsigned int ...Ns = {1, 2, 4, 8, 16, 32, 64, 128}]::<lambda()>{}}, {1, 2, 4, 8, 16, 32, 64, 128, <lambda closure object>run(const Params&, const std::vector<long unsigned int>&, const std::vector<long unsigned int>&) [with long unsigned int ...Ns = {1, 2, 4, 8, 16, 32, 64, 128}]::<lambda()>{}}, {1, 2, 4, 8, 16, 32, 64, 128, <lambda closure object>run(const Params&, const std::vector<long unsigned int>&, const std::vector<long unsigned int>&) [with long unsigned int ...Ns = {1, 2, 4, 8, 16, 32, 64, 128}]::<lambda()>{}}, {1, 2, 4, 8, 16, 32, 64, 128, <lambda closure object>run(const Params&, const std::vector<long unsigned int>&, const std::vector<long unsigned int>&) [with long unsigned int ...Ns = {1, 2, 4, 8, 16, 32, 64, 128}]::<lambda()>{}}, {1, 2, 4, 8, 16, 32, 64, 128, <lambda closure object>run(const Params&, const std::vector<long unsigned int>&, const std::vector<long unsigned int>&) [with long unsigned int ...Ns = {1, 2, 4, 8, 16, 32, 64, 128}]::<lambda()>{}}, {1, 2, 4, 8, 16, 32, 64, 128, <lambda closure object>run(const Params&, const std::vector<long unsigned int>&, const std::vector<long unsigned int>&) [with long unsigned int ...Ns = {1, 2, 4, 8, 16, 32, 64, 128}]::<lambda()>{}}, {1, 2, 4, 8, 16, 32, 64, 128, <lambda closure object>run(const Params&, const std::vector<long unsigned int>&, const std::vector<long unsigned int>&) [with long unsigned int ...Ns = {1, 2, 4, 8, 16, 32, 64, 128}]::<lambda()>{}}}' from '<brace-enclosed initializer list>' to 'std::unordered_map<long unsigned int, std::function<const std::vector<std::pair<long unsigned int, std::basic_string<char> > >()> >'
   std::unordered_map<size_t, std::function<const std::vector<Device>()>> enumerate = {{Ns, []() {
                                                                                   ^~~~~~~~~
/tmp/miniBUDE/src/main.cpp:487:78: error: could not convert '{{1, 2, 4, 8, 16, 32, 64, 128, <lambda closure object>run(const Params&, const std::vector<long unsigned int>&, const std::vector<long unsigned int>&) [with long unsigned int ...Ns = {1, 2, 4, 8, 16, 32, 64, 128}]::<lambda(size_t, size_t)>{(* & p)}}, {1, 2, 4, 8, 16, 32, 64, 128, <lambda closure object>run(const Params&, const std::vector<long unsigned int>&, const std::vector<long unsigned int>&) [with long unsigned int ...Ns = {1, 2, 4, 8, 16, 32, 64, 128}]::<lambda(size_t, size_t)>{(* & p)}}, {1, 2, 4, 8, 16, 32, 64, 128, <lambda closure object>run(const Params&, const std::vector<long unsigned int>&, const std::vector<long unsigned int>&) [with long unsigned int ...Ns = {1, 2, 4, 8, 16, 32, 64, 128}]::<lambda(size_t, size_t)>{(* & p)}}, {1, 2, 4, 8, 16, 32, 64, 128, <lambda closure object>run(const Params&, const std::vector<long unsigned int>&, const std::vector<long unsigned int>&) [with long unsigned int ...Ns = {1, 2, 4, 8, 16, 32, 64, 128}]::<lambda(size_t, size_t)>{(* & p)}}, {1, 2, 4, 8, 16, 32, 64, 128, <lambda closure object>run(const Params&, const std::vector<long unsigned int>&, const std::vector<long unsigned int>&) [with long unsigned int ...Ns = {1, 2, 4, 8, 16, 32, 64, 128}]::<lambda(size_t, size_t)>{(* & p)}}, {1, 2, 4, 8, 16, 32, 64, 128, <lambda closure object>run(const Params&, const std::vector<long unsigned int>&, const std::vector<long unsigned int>&) [with long unsigned int ...Ns = {1, 2, 4, 8, 16, 32, 64, 128}]::<lambda(size_t, size_t)>{(* & p)}}, {1, 2, 4, 8, 16, 32, 64, 128, <lambda closure object>run(const Params&, const std::vector<long unsigned int>&, const std::vector<long unsigned int>&) [with long unsigned int ...Ns = {1, 2, 4, 8, 16, 32, 64, 128}]::<lambda(size_t, size_t)>{(* & p)}}, {1, 2, 4, 8, 16, 32, 64, 128, <lambda closure object>run(const Params&, const std::vector<long unsigned int>&, const std::vector<long unsigned int>&) [with long unsigned int ...Ns = {1, 2, 4, 8, 16, 32, 64, 128}]::<lambda(size_t, size_t)>{(* & p)}}}' from '<brace-enclosed initializer list>' to 'std::unordered_map<long unsigned int, std::function<const Sample(long unsigned int, long unsigned int)> >'
   std::unordered_map<size_t, std::function<const Sample(size_t, size_t)>> kernel = {
```